name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:

  tests-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add project to PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest tests/test_unit.py

      - name: Use SQLite for integration tests
        run: echo "DATABASE_URL=sqlite:///:memory:" >> $GITHUB_ENV

      - name: Run integration tests
        run: pytest tests/test_integration.py


  docker-push:
    needs: tests-and-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build production image
        run: |
          docker build -t ktzkvin/taskmanager:latest .

      - name: Push to Dockerhub
        run: docker push ktzkvin/taskmanager:latest
